Improve plugin logic to support signing .app and .framework files, and add entitlements.
- Add support for `.app` and `.framework` files
- Add support for signing sub-items in app and frameworks.
- Add support for passing entitlement files
- Simplify YAML
- Remove unnecessary error handling already done by pipefail

Co-authored-by: Sean Robertson <seanrobertson@improbable.io>

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -23,15 +23,10 @@ default_keychain_pw_helper_script="${script_root_dir}/../helpers/fetch-keychain-
 #   fetch_target: Name of the BuildKite artifact to fetch
 #   dest_dir: Where to download it to.
 function fetch_artifact() {
-  fetch_target="${1}"
-  dest_dir="${2}"
+  local fetch_target="${1}"
+  local dest_dir="${2}"
 
   buildkite-agent artifact download "${fetch_target}" "${dest_dir}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "Unable to download the specified artifact '${fetch_target}' with error code '${retval}'"
-    exit 1
-  fi
 
   echo "${dest_dir}/${fetch_target}"
 }
@@ -39,18 +34,12 @@ function fetch_artifact() {
 # If the unlock secret was not supplied as an env var, call the helper script to fetch it
 # Params:
 #   helper_script_path: Path to a script to run that returns the keychain PW.
-#   helper_script_arg: Any arguments that need to be passed to the helper script.
+#   rest: Any arguments that need to be passed to the helper script.
 function get_keychain_pw() {
-  helper_script_path="${1}"
-  helper_script_arg="${2}"
+  local helper_script_path="${1}"
 
-  if [[ -z "${KEYCHAIN_PW}" ]]; then
-    KEYCHAIN_PW="$("${helper_script_path}" "${helper_script_arg}")"
-    retval=$?
-    if [[ "${retval}" -ne 0 || -z "${KEYCHAIN_PW}" ]]; then
-      echo "Unable the fetch the secret using the helper script: error code '${retval}'"
-      exit 2
-    fi
+  if [[ -z "${KEYCHAIN_PW:-}" ]]; then
+    KEYCHAIN_PW="$("${helper_script_path}" "${@:2}")"
   fi
 
   echo "${KEYCHAIN_PW}"
@@ -61,32 +50,30 @@ function get_keychain_pw() {
 #   keychain_name: The name of an existing, accessible macos Keychain containing one signing certificate.
 #   keychain_pw: The password to unlock this keychain.
 function unlock_keychain() {
-  keychain_name=${1}
-  keychain_pw=${2}
+  local keychain_name=${1}
+  local keychain_pw=${2}
 
   security unlock-keychain -p "${keychain_pw}" "${keychain_name}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "Unable to unlock the requested keychain '${keychain_name}': error code '${retval}'"
-    exit 3
-  fi
 }
 
 # Generate gon config for signing+notarization
 # Params:
-#   input: File to sign+notarize
-#   signed_dir_fragment: path to store any new files generated by this step in
+#   prerequisites: variable stub to get list of prerequisites from YAML definition
+#   entitlements: path to entitlements file (ignored if empty)
+#   artifacts_dir: root path to relevant artifacts
+#   config_path: path to write gon config file to
 function generate_signing_config() {
-  input="${1}"
-  signed_dir_fragment="${2}"
+  local prerequisites="${1}"
+  local entitlements="${2}"
+  local artifacts_dir="${3}"
+  local config_path="${4}"
 
-  config=$(jq -n \
-    --arg input "${input}" \
+  jq -n \
     --arg bundle_id "${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_BUNDLE_ID}" \
     --arg apple_user_email "${BUILDKITE_PLUGIN_MAC_CODESIGN_APPLE_USER_EMAIL}" \
     --arg identity "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" \
     '{
-      "source": [$input],
+      "source": [],
       "bundle_id": $bundle_id,
       "apple_id": {
         "username": $apple_user_email,
@@ -95,44 +82,39 @@ function generate_signing_config() {
       "sign": {
         "application_identity": $identity,
       },
-    }')
+    }' >"${config_path}"
 
-  # Generate DMG files if relevant
-  tool_name="${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_NAME}"
-  if [[ -n "${tool_name}" ]]; then
-    dmg_name="${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_DMG_NAME}"
-    if [[ -z "${dmg_name}" ]]; then
-      dmg_name="${tool_name}.dmg"
-    fi
+  echo "${prerequisites}" | while read -r prereq; do
+    # iterate over prerequisites, adding them to the codesign config
+    local config
+    config="$(jq --arg toSign "${artifacts_dir}/${prereq}" '.source += [$toSign]' "${config_path}")"
+    echo "${config}" >"${config_path}"
+  done
 
-    config="$(
-      echo "${config}" | jq \
-        --arg name "${tool_name}" \
-        --arg path "${signed_dir_fragment}/${dmg_name}" \
-        '"dmg": {
-          "volume_name": $name,
-          "output_path": $path,
-        }'
-    )"
+  if [[ -n "${entitlements}" ]]; then
+    # if entitlements specified, add them to config.
+    local config
+    config="$(jq --arg entitlements "${entitlements}" '.sign.entitlements_file = $entitlements' "${config_path}")"
+    echo "${config}" >"${config_path}"
   fi
-
-  echo "${config}"
 }
 
 # Generate gon config for notarization
 # Params:
-#   input: File to notarize
+#   inputfile: File to notarize
+#   config_path: Path to config
 function generate_notarization_config() {
-  input="${1}"
+  local inputfile="${1}"
+  local config_path="${2}"
 
   jq -n \
-    --arg input "${input}" \
+    --arg inputfile "${inputfile}" \
     --arg bundle_id "${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_BUNDLE_ID}" \
     --arg apple_user_email "${BUILDKITE_PLUGIN_MAC_CODESIGN_APPLE_USER_EMAIL}" \
     '{
       "notarize": [
         {
-        "path": $input,
+        "path": $inputfile,
         "bundle_id": $bundle_id,
         "staple": true,
         }
@@ -141,75 +123,64 @@ function generate_notarization_config() {
         "username": $apple_user_email,
         "password": "@keychain:apple_password",
       },
-    }'
+    }' >"${config_path}"
 }
 
-# Go through the necessary steps to sign an artifact and place the signed result in the output directory.
+# Handle all the requirements for signing code.
 # Params:
-#   input: File to notarize
-#   signed_dir_fragment: output folder
-function sign_and_notarize() {
-  unsigned_artifact="${1}"
-  signed_dir_fragment="${2}"
+#   artifact: File to sign+notarize
+#   config_path: Path to gon config
+#   prerequisites: Files to sign before signing final artifact
+#   entitlements: Path to entitlements plist
+#   artifact_dir: Directory where prerequisites are stored.
+function sign_code() {
+  local artifact="${1}"
+  local config_path="${2}"
+  local prerequisites="${3}"
+  local entitlements="${4}"
+  local artifact_dir="${5}"
 
-  signed_artifact="${signed_dir_fragment}/$(basename "${unsigned_artifact}")"
-  config_path="${signed_dir_fragment}/config.json"
+  # generate config
+  echo "${artifact}: Generating codesigning + notarization config"
+  generate_signing_config "${prerequisites}" "${entitlements}" "${artifact_dir}" "${config_path}"
 
-  if [[ "${unsigned_artifact}" == *.pkg ]]; then
-    # PKG files need to be signed with "Developer ID Installer" certs through `productsign`.
-    # `gon` only supports "Application" certs, through `codesign`.
-    # This steps signs with productsign, and then generates a gon config to notarize it.
-
-    echo "${unsigned_artifact}: signing PKG file"
-    productsign --sign "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" "${unsigned_artifact}" "${signed_artifact}"
-    retval=$?
-    if [[ "${retval}" -ne 0 ]]; then
-      echo "productsigning of target '${unsigned_artifact}' failed: error code '${retval}'"
-      exit 4
-    fi
-
-    echo "${signed_artifact}: generating package notarization config"
-    generate_notarization_config "${signed_artifact}" >"${config_path}"
-  else
-
-    # `gon` uses `codesign`, which signs in-place; so move file to correct directory
-    cp "${unsigned_artifact}" "${signed_artifact}"
-
-    echo "${signed_artifact}: generating code signing + notarization config"
-    generate_signing_config "${signed_artifact}" "${signed_dir_fragment}" >"${config_path}"
-  fi
-
-  # Use `gon` config generated in earlier steps to sign (if necessary) and notarize.
-  echo "${artifact}: executing gon on generated config"
+  echo "${artifact}: Executing gon on generated config"
   gon "${config_path}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "notarization of target '${unsigned_artifact}' failed: error code '${retval}'"
-    exit 5
-  fi
+}
+
+# Handle all the requirements for signing packages.
+# Params:
+#   artifact: pkg file to sign+notarize.
+#   signed_artifact: outputpath of signed pkg.
+#   config_path: Path to gon config
+function sign_pkg() {
+  local artifact="${1}"
+  local signed_artifact="${2}"
+  local config_path="${3}"
+
+  echo "${artifact}: signing PKG file"
+  productsign --sign "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" "${artifact}" "${signed_artifact}"
+
+  echo "${artifact}: Generating package notarization config"
+  generate_notarization_config "${signed_artifact}" "${config_path}"
+
+  echo "${artifact}: notarizing through gon"
+  gon "${config_path}"
 }
 
 # Convenience wrapper to upload our signed artifact to BuildKite
 # Params:
 #   artifact: Path of a file to upload to BuildKite as an artifact.
 function upload_artifact() {
-  artifact="${1}"
+  local artifact="${1}"
 
   buildkite-agent artifact upload "${artifact}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "Unable to upload ${artifact} to BuildKite: error code '${retval}'"
-    exit 6
-  fi
 }
 
 # Allow the user to override the default keychain pw retrieval helper script.
 function find_keychain_pw_helper_script() {
-  if [[ -n "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT}" ]]; then
-    script="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT}"
-  else
-    script="${default_keychain_pw_helper_script}"
-  fi
+  local script
+  script="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT:-${default_keychain_pw_helper_script}}"
 
   echo "${script}"
 }
@@ -228,27 +199,59 @@ echo "--- Setting up local directories"
 # Download things in a local dir to identify them
 artifact_dir_fragment="artifacts"
 rm -rf "${artifact_dir_fragment}" && mkdir -p "${artifact_dir_fragment}"
-relative_artifacts_dir="$(pwd)/${artifact_dir_fragment}"
 
-# Signed things go in a local dir so the uploaded artifacts don't have a weird path
 signed_dir_fragment="signed"
 rm -rf "${signed_dir_fragment}" && mkdir -p "${signed_dir_fragment}"
+# Do not use absolute path to avoid polluting artifact names
 
-# Download and sign each requested artifact
-for artifact in $(plugin_read_list INPUT_ARTIFACTS); do
-  echo "--- Signing ${artifact}"
+# Download entitlements
+entitlements="${BUILDKITE_PLUGIN_MAC_CODESIGN_ENTITLEMENTS:-}"
+if [[ -n "${entitlements}" ]]; then
+  fetch_artifact "${entitlements}" "${artifact_dir_fragment}"
+  entitlements="${artifact_dir_fragment}/${entitlements}"
+fi
 
-  echo "${artifact}: retrieving unsigned artifact"
-  unsigned_artifact="$(fetch_artifact "${artifact}" "${relative_artifacts_dir}")"
+## Download requested artifact
+artifact="${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}"
+echo "${artifact}: retrieving unsigned artifact"
 
-  sign_and_notarize "${unsigned_artifact}" "${signed_dir_fragment}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "failed to sign and notarize '${unsigned_artifact}': error code '${retval}'"
-    exit ${retval}
-  fi
+if [[ "${artifact}" == *"*"* ]]; then
+  echo "inputfile artifacts cannot contain wildcards: '${artifact}'"
+  exit 5
+fi
 
-done
+# If .app or .framework, handle as a directory.
+if [[ "${artifact}" == *".app" || "${artifact}" == *".framework" ]]; then
+  fetch_artifact "${artifact}/**/*" "${artifact_dir_fragment}"
+else
+  fetch_artifact "${artifact}" "${artifact_dir_fragment}"
+fi
 
-echo "--- Uploading artifacts"
+unsigned_artifact="${artifact_dir_fragment}/${artifact}"
+signed_artifact="${signed_dir_fragment}/${artifact}"
+
+# Make sure dir structure exists
+mkdir -p "$(dirname "${signed_artifact}")"
+
+config_path="${signed_dir_fragment}/config.json"
+
+prerequisites="$(plugin_read_list SIGN_PREREQUISITES)"
+if [[ -z "${prerequisites}" ]]; then
+  # If no prerequisites are specified, point to the artifact
+  prerequisites="${unsigned_artifact}"
+fi
+
+if [[ "${artifact}" == *".pkg" ]]; then
+  # PKG files need to be signed with "Developer ID Installer" certs through `productsign`.
+  # `gon` only supports "Application" certs, through `codesign`.
+  # This steps signs with productsign, and then generates a gon config to notarize it.
+  sign_pkg "${unsigned_artifact}" "${signed_artifact}" "${config_path}"
+else
+  sign_code "${unsigned_artifact}" "${config_path}" "${prerequisites}" "${entitlements}" "${artifact_dir_fragment}"
+
+  # codesign is in-place, so move artifacts to signed artifacts
+  mv "${unsigned_artifact}" "${signed_artifact}"
+fi
+
+echo "--- Uploading output artifacts"
 upload_artifact "${signed_dir_fragment}/**/*"
