Rework to support .app files and entitlements, remove pkg support since thats productsigning, not codesign.

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -23,8 +23,8 @@ default_keychain_pw_helper_script="${script_root_dir}/../helpers/fetch-keychain-
 #   fetch_target: Name of the BuildKite artifact to fetch
 #   dest_dir: Where to download it to.
 function fetch_artifact() {
-  fetch_target="${1}"
-  dest_dir="${2}"
+  local fetch_target="${1}"
+  local dest_dir="${2}"
 
   buildkite-agent artifact download "${fetch_target}" "${dest_dir}"
   retval=$?
@@ -39,13 +39,12 @@ function fetch_artifact() {
 # If the unlock secret was not supplied as an env var, call the helper script to fetch it
 # Params:
 #   helper_script_path: Path to a script to run that returns the keychain PW.
-#   helper_script_arg: Any arguments that need to be passed to the helper script.
+#   rest: Any arguments that need to be passed to the helper script.
 function get_keychain_pw() {
-  helper_script_path="${1}"
-  helper_script_arg="${2}"
+  local helper_script_path="${1}"
 
-  if [[ -z "${KEYCHAIN_PW}" ]]; then
-    KEYCHAIN_PW="$("${helper_script_path}" "${helper_script_arg}")"
+  if [[ -z "${KEYCHAIN_PW:-}" ]]; then
+    KEYCHAIN_PW="$("${helper_script_path}" "${@:2}")"
     retval=$?
     if [[ "${retval}" -ne 0 || -z "${KEYCHAIN_PW}" ]]; then
       echo "Unable the fetch the secret using the helper script: error code '${retval}'"
@@ -61,8 +60,8 @@ function get_keychain_pw() {
 #   keychain_name: The name of an existing, accessible macos Keychain containing one signing certificate.
 #   keychain_pw: The password to unlock this keychain.
 function unlock_keychain() {
-  keychain_name=${1}
-  keychain_pw=${2}
+  local keychain_name=${1}
+  local keychain_pw=${2}
 
   security unlock-keychain -p "${keychain_pw}" "${keychain_name}"
   retval=$?
@@ -74,19 +73,22 @@ function unlock_keychain() {
 
 # Generate gon config for signing+notarization
 # Params:
-#   input: File to sign+notarize
-#   signed_dir_fragment: path to store any new files generated by this step in
+#   prerequisites: variable stub to get list of prerequisites from YAML definition
+#   entitlements: path to entitlements file (ignored if empty)
+#   absolute_artifacts_dir: root path to artifacts
+#   config_path: path to write gon config file to
 function generate_signing_config() {
-  input="${1}"
-  signed_dir_fragment="${2}"
+  local prerequisites="${1}"
+  local entitlements="${2}"
+  local absolute_artifacts_dir="${3}"
+  local config_path="${4}"
 
-  config=$(jq -n \
-    --arg input "${input}" \
+  jq -n \
     --arg bundle_id "${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_BUNDLE_ID}" \
     --arg apple_user_email "${BUILDKITE_PLUGIN_MAC_CODESIGN_APPLE_USER_EMAIL}" \
     --arg identity "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" \
     '{
-      "source": [$input],
+      "source": [],
       "bundle_id": $bundle_id,
       "apple_id": {
         "username": $apple_user_email,
@@ -95,28 +97,21 @@ function generate_signing_config() {
       "sign": {
         "application_identity": $identity,
       },
-    }')
+    }' >"${config_path}"
 
-  # Generate DMG files if relevant
-  tool_name="${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_NAME}"
-  if [[ -n "${tool_name}" ]]; then
-    dmg_name="${BUILDKITE_PLUGIN_MAC_CODESIGN_TOOL_DMG_NAME}"
-    if [[ -z "${dmg_name}" ]]; then
-      dmg_name="${tool_name}.dmg"
-    fi
+  echo "${prerequisites}" | while read -r prereq; do
+    # iterate over prerequisites, adding them to the codesign config
+    local config
+    config="$(jq --arg toSign "${absolute_artifacts_dir}/${prereq}" '.source += [$toSign]' "${config_path}")"
+    echo "${config}" >"${config_path}"
+  done
 
-    config="$(
-      echo "${config}" | jq \
-        --arg name "${tool_name}" \
-        --arg path "${signed_dir_fragment}/${dmg_name}" \
-        '"dmg": {
-          "volume_name": $name,
-          "output_path": $path,
-        }'
-    )"
+  if [[ -n "${entitlements}" ]]; then
+    # if entitlements specified, add them to config.
+    local config
+    config="$(jq --arg entitlements "${entitlements}" '.sign.entitlements_file = $entitlements' "${config_path}")"
+    echo "${config}" >"${config_path}"
   fi
-
-  echo "${config}"
 }
 
 # Generate gon config for notarization
@@ -144,56 +139,11 @@ function generate_notarization_config() {
     }'
 }
 
-# Go through the necessary steps to sign an artifact and place the signed result in the output directory.
-# Params:
-#   input: File to notarize
-#   signed_dir_fragment: output folder
-function sign_and_notarize() {
-  unsigned_artifact="${1}"
-  signed_dir_fragment="${2}"
-
-  signed_artifact="${signed_dir_fragment}/$(basename "${unsigned_artifact}")"
-  config_path="${signed_dir_fragment}/config.json"
-
-  if [[ "${unsigned_artifact}" == *.pkg ]]; then
-    # PKG files need to be signed with "Developer ID Installer" certs through `productsign`.
-    # `gon` only supports "Application" certs, through `codesign`.
-    # This steps signs with productsign, and then generates a gon config to notarize it.
-
-    echo "${unsigned_artifact}: signing PKG file"
-    productsign --sign "${BUILDKITE_PLUGIN_MAC_CODESIGN_CERT_IDENTITY}" "${unsigned_artifact}" "${signed_artifact}"
-    retval=$?
-    if [[ "${retval}" -ne 0 ]]; then
-      echo "productsigning of target '${unsigned_artifact}' failed: error code '${retval}'"
-      exit 4
-    fi
-
-    echo "${signed_artifact}: generating package notarization config"
-    generate_notarization_config "${signed_artifact}" >"${config_path}"
-  else
-
-    # `gon` uses `codesign`, which signs in-place; so move file to correct directory
-    cp "${unsigned_artifact}" "${signed_artifact}"
-
-    echo "${signed_artifact}: generating code signing + notarization config"
-    generate_signing_config "${signed_artifact}" "${signed_dir_fragment}" >"${config_path}"
-  fi
-
-  # Use `gon` config generated in earlier steps to sign (if necessary) and notarize.
-  echo "${artifact}: executing gon on generated config"
-  gon "${config_path}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "notarization of target '${unsigned_artifact}' failed: error code '${retval}'"
-    exit 5
-  fi
-}
-
 # Convenience wrapper to upload our signed artifact to BuildKite
 # Params:
 #   artifact: Path of a file to upload to BuildKite as an artifact.
 function upload_artifact() {
-  artifact="${1}"
+  local artifact="${1}"
 
   buildkite-agent artifact upload "${artifact}"
   retval=$?
@@ -205,7 +155,8 @@ function upload_artifact() {
 
 # Allow the user to override the default keychain pw retrieval helper script.
 function find_keychain_pw_helper_script() {
-  if [[ -n "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT}" ]]; then
+  local script
+  if [[ -n "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT:-}" ]]; then
     script="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN_PW_HELPER_SCRIPT}"
   else
     script="${default_keychain_pw_helper_script}"
@@ -221,34 +172,49 @@ echo "--- Getting the password to unlock the keychain"
 keychain_pw_helper_script=$(find_keychain_pw_helper_script)
 keychain_pw=$(get_keychain_pw "${keychain_pw_helper_script}")
 
-echo "--- Unlocking the keychain"
+#echo "--- Unlocking the keychain"
 unlock_keychain "${codesigning_keychain}" "${keychain_pw}"
 
 echo "--- Setting up local directories"
 # Download things in a local dir to identify them
 artifact_dir_fragment="artifacts"
 rm -rf "${artifact_dir_fragment}" && mkdir -p "${artifact_dir_fragment}"
-relative_artifacts_dir="$(pwd)/${artifact_dir_fragment}"
+absolute_artifacts_dir="$(pwd)/${artifact_dir_fragment}"
 
-# Signed things go in a local dir so the uploaded artifacts don't have a weird path
-signed_dir_fragment="signed"
-rm -rf "${signed_dir_fragment}" && mkdir -p "${signed_dir_fragment}"
-
-# Download and sign each requested artifact
-for artifact in $(plugin_read_list INPUT_ARTIFACTS); do
-  echo "--- Signing ${artifact}"
-
+## Download and sign each requested artifact
+plugin_read_list INPUT_ARTIFACTS | while read -r artifact; do
   echo "${artifact}: retrieving unsigned artifact"
-  unsigned_artifact="$(fetch_artifact "${artifact}" "${relative_artifacts_dir}")"
-
-  sign_and_notarize "${unsigned_artifact}" "${signed_dir_fragment}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "failed to sign and notarize '${unsigned_artifact}': error code '${retval}'"
-    exit ${retval}
-  fi
-
+  fetch_artifact "${artifact}" "${absolute_artifacts_dir}"
 done
 
-echo "--- Uploading artifacts"
-upload_artifact "${signed_dir_fragment}/**/*"
+entitlements="${BUILDKITE_PLUGIN_MAC_CODESIGN_ENTITLEMENTS}"
+if [[ -n "${entitlements}" ]]; then
+  #  fetch_artifact "${entitlements}" "${absolute_artifacts_dir}"
+  entitlements="${absolute_artifacts_dir}/${entitlements}"
+fi
+
+config_path="config.json"
+prerequisites="$(plugin_read_list SIGN_PREREQUISITES)"
+
+# generate config
+echo "-- Generating signing config"
+generate_signing_config "${prerequisites}" "${entitlements}" "${absolute_artifacts_dir}" "${config_path}"
+
+echo "-- Executing gon on generated config"
+gon "${config_path}"
+retval=$?
+if [[ "${retval}" -ne 0 ]]; then
+  echo "notarization failed: error code '${retval}'"
+  exit 5
+fi
+
+echo "--- Uploading output artifacts"
+# upload config
+echo "${config_path}: uploading config used"
+upload_artifact "${config_path}"
+
+# upload signed items
+plugin_read_list OUTPUT_ARTIFACTS | while read -r artifact; do
+  echo "${artifact}: uploading signed artifact"
+  upload_artifact "${absolute_artifacts_dir}/${artifact}"
+done
