cleanup to stop reading term output as file name

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -144,53 +144,6 @@ function generate_notarisation_config() {
     }'
 }
 
-# Sign the binary
-# Params:
-#   signing_target: The unsigned item to sign.
-#   signed_dir_fragment: path to store any new files generated by this step in
-function sign_and_validate() {
-  signing_target="${1}"
-  signed_dir_fragment="${2}"
-
-  config_path="${signed_dir_fragment}/config.json"
-  if [[ "${signing_target}" == *.pkg ]]; then
-    # PKG files need to be signed with "developer ID Installer" certs through `productsign`.
-    # `gon` only supports "Application" certs, through `codesign`.
-    # This steps signs with productsign, and then generates a gon config to notarize it.
-    echo "${signing_target}: signing pkg"
-    signed_artifact="$(basename "${signing_target}")"
-
-    echo "${signing_target}: signing PKG file"
-    productsign --sign "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEY_WANTED}" "${signing_target}" "${signed_dir_fragment}/${signed_artifact}"
-    retval=$?
-    if [[ "${retval}" -ne 0 ]]; then
-      echo "productsigning of target '${signing_target}' failed: error code '${retval}'"
-      exit 4
-    fi
-
-    output_file="${signed_artifact}"
-
-    echo "${signing_target}: generating package notarisation config"
-    generate_notarisation_config "${signed_artifact}" >"${config_path}"
-  else
-    output_file="${signing_target}"
-
-    echo "${signing_target}: generating code signing + notarisation config"
-    generate_signing_config "${signing_target}" "${signed_dir_fragment}" >"${config_path}"
-  fi
-
-  # Use `gon` config generated in earlier steps to sign (if necessary) and notarise.
-  echo "${signing_target}: executing gon on generated config"
-  gon --log-level=info "${config_path}"
-  retval=$?
-  if [[ "${retval}" -ne 0 ]]; then
-    echo "codesigning of target '${signing_target}' failed: error code '${retval}'"
-    exit 4
-  fi
-
-  echo "${output_file}"
-}
-
 # Convenience wrapper to upload our signed artifact to BuildKite
 # Params:
 #   artifact: Path of a file to upload to BuildKite as an artifact.
@@ -243,15 +196,45 @@ for artifact in $(plugin_read_list INPUT_ARTIFACTS); do
   echo "${artifact}: retrieving unsigned artifact"
   unsigned_artifact="$(fetch_artifact "${artifact}" "${relative_artifacts_dir}")"
 
-  echo "${artifact}: signing + notarising artifact"
-  signed_artifact="$(sign_and_validate "${unsigned_artifact}" "${signed_dir_fragment}")"
+  signed_artifact="${signed_dir_fragment}/$(basename "${unsigned_artifact}")"
 
-  signed_file="$(basename "${signed_artifact}")"
+  config_path="${signed_dir_fragment}/config.json"
+  if [[ "${unsigned_artifact}" == *.pkg ]]; then
+    # PKG files need to be signed with "developer ID Installer" certs through `productsign`.
+    # `gon` only supports "Application" certs, through `codesign`.
+    # This steps signs with productsign, and then generates a gon config to notarize it.
+    echo "${unsigned_artifact}: signing pkg"
 
-  echo "${signed_file}: uploading signed artifact"
-  # Move the signed file to the "signed/" directory for uploading with a normal-looking name.
-  # This way, the uploaded artifacts in BK will all be named "signed/$ARTIFACT_FILENAME"
-  mv "${signed_artifact}" "${signed_dir_fragment}/${signed_file}"
-  upload_artifact "${signed_dir_fragment}/**/*"
-  popd
+    echo "${unsigned_artifact}: signing PKG file"
+    productsign --sign "${BUILDKITE_PLUGIN_MAC_CODESIGN_KEY_WANTED}" "${unsigned_artifact}" "${signed_artifact}"
+    retval=$?
+    if [[ "${retval}" -ne 0 ]]; then
+      echo "productsigning of target '${unsigned_artifact}' failed: error code '${retval}'"
+      exit 4
+    fi
+
+    echo "${unsigned_artifact}: generating package notarisation config"
+    generate_notarisation_config "${unsigned_artifact}" >"${config_path}"
+  else
+
+    # `gon` uses `codesign`, which signs in-place; so move file to correct directory
+    cp "${unsigned_artifact}" "${signed_artifact}"
+    signed_artifact="${unsigned_artifact}"
+
+    echo "${unsigned_artifact}: generating code signing + notarisation config"
+    generate_signing_config "${signed_artifact}" "${signed_dir_fragment}" >"${config_path}"
+  fi
+
+  # Use `gon` config generated in earlier steps to sign (if necessary) and notarise.
+  echo "${artifact}: executing gon on generated config"
+  gon "${config_path}"
+  retval=$?
+  if [[ "${retval}" -ne 0 ]]; then
+    echo "codesigning of target '${unsigned_artifact}' failed: error code '${retval}'"
+    exit 4
+  fi
+
 done
+
+echo "--- Uploading artifacts"
+upload_artifact "${signed_dir_fragment}/**/*"
