More working, except now it's pretty near a brick wall.

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -2,18 +2,47 @@
 #
 # Now that we have a constructed codesigning environment, sign the code.
 
+[[ -n "${DEBUG-}" ]] && set -x
 
 artifact_dir=$(mktemp -d)
+### TESTING
+cp imp-ci "${artifact_dir}"
+### TESTING
 pushd "${artifact_dir}"
 
-# Step 1: Retrieve the artifact to sign.
-# TODO: Bail out on any errors
-buildkite-agent artifact download "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}" .
+# Retrieve the artifact to sign.
+# buildkite-agent artifact download "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}" .
+# retval=$?
+# if [[ "${retval}" -ne 0  ]]; then
+#   echo "Unable to download the specified artifact '${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}' with error code '${retval}'"
+#   exit 1
+# fi
+signing_target=$(ls -1 .)
 
-# Step 2: Sign it with the cert specified.
-# TODO: Validate the return code.
-codesign -s "${CODESIGN_IDENTITY}" "${target_binary}"
+# Unlock the keychain, since the setup set left it locked.
+# security unlock-keychain -p "${KEYCHAIN_PW}" codesign.keychain
 
-# Step 3: Store the signed artifact in the bucket.
-# TODO: Handle errors
-buildkite-agent artifact upload "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}"
+# Sign it with the cert specified.
+# codesign -s "${CODESIGN_IDENTITY}" "${signing_target}"
+codesign --verify --verbose --display --deep -s "${CODESIGN_IDENTITY}" ${signing_target}
+retval=$?
+if [[ "${retval}" -ne 0  ]]; then
+  echo "codesigning of target '${signing_target}' failed with error code '${retval}'"
+  exit 2
+fi
+
+# Validate that the target now has the expected signature.
+codesign --verify --deep --strict --verbose= "${signing_target}"
+retval=$?
+if [[ "${retval}" -ne 0  ]]; then
+  echo "Unable to verify that '${signing_target}' has a valid code signature: error code '${retval}'"
+  exit 3
+fi
+
+# Store the signed artifact back in the bucket.
+# buildkite-agent artifact upload "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}"
+# retval=$?
+# if [[ "${retval}" -ne 0  ]]; then
+#   echo "Unable to upload signed target '${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}' to artifact bucket with error code '${retval}'"
+#   exit 4
+# fi
diff --git a/hooks/environment b/hooks/environment
--- a/hooks/environment
+++ b/hooks/environment
@@ -7,19 +7,27 @@
 # 3. Create a temporary keychain, import the signing cert into it, then lock the keychain with a rand pw.
 # 4. Export the codesigning identity ID and the keychain password so the rest of this job can sign with them.
 
+[[ -n "${DEBUG-}" ]] && set -x
+
 signing_cert_name="${BUILDKITE_PLUGIN_MAC_CODESIGN_SIGNING_CERT}"
 pw_secret="${BUILDKITE_PLUGIN_MAC_CODESIGN_SIGNING_CERT_PW_SECRET}"
 
-# TODO: Make this be a useful path.
-cert_store_root_path="/Users/sean/src/cert-root"
+cert_store_root_path="/Users/buildkite-agent/signing-certs"
 # TODO: Make this be the actual signing host, not my laptop.
 permitted_signing_host="sean-mac-c02xv3a8jgh6"
-codesign_keychain="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN}:-codesign.keychain"
+codesign_keychain="${BUILDKITE_PLUGIN_MAC_CODESIGN_KEYCHAIN:-codesign.keychain}"
 cert_pw=""
 signing_cert_path="${cert_store_root_path}/${signing_cert_name}"
 
 # Verify that this is only running on MacOS, via BuildKite, in proper CI, on our blessed agent.
 validate_environment() {
+  if [[ ! -r "${signing_cert_path}" ]]; then
+    echo "Unable to find/read specified signing cert ${signing_cert} in ${cert_store_root_path}"
+    exit 1
+  else
+    echo "Found cert!"
+  fi
+
   if [[ "${BUILDKITE}" != "true" ]]; then
     echo "Code signing can only be done as part of a BuildKite pipeline."
     exit 1
@@ -39,27 +47,18 @@ validate_environment() {
     echo "Code signing can only be performed on specific permitted agents."
     exit 1
   fi
-
-  if [[ ! -r "${signing_cert_path}" ]]; then
-    echo "Unable to read specified signing cert ${signing_cert} in ${cert_store_root_path}"
-    return 1
-  else
-    echo "Found cert!"
-    cat "${signing_cert_path}"
-  fi
 }
 
 # Retrieve the pw for the signing cert from Vault.
 # Required param: 
 #   name of the secret to retrieve from Vault
 retrieve_signing_cert_pw() {
-  cert_pw=$(imp-vault read-key --key="${1}")
+  cert_pw=$(imp-vault read-key --key="${1}" --field=token)
   if [[ $? -ne 0 || "${cert_pw}" == "" ]]; then
     echo "Unable to read secret for specified secret ${1}"
-    return 1
+    exit 1
   else
     echo "Successfully read secret from Vault"
-    echo "${cert_pw}"
   fi
 }
 
@@ -73,7 +72,7 @@ create_codesign_keychain() {
   
   # If the keychain already exists, warn the user and then delete it so we start fresh.
   security list-keychains | grep "${1}"
-  if [[ $? -ne 0  ]]; then
+  if [[ $? -eq 0  ]]; then
     echo "WARNING: The keychain ${1} already exists.  Removing it and creating a new empty keychain."
     security delete-keychain "${1}"
   fi
@@ -96,7 +95,7 @@ add_certificate_to_keychain() {
   export CODESIGN_IDENTITY="$(security find-identity codesign.keychain | grep -A1 "Valid identities" | tail -1 | awk '{print $2}')"
   
   # Lock it up, juuuuust in case.
-  security lock-keychain "${2}"
+  # security lock-keychain "${2}"
 }
 
 validate_environment
