a bit of polish

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -7,23 +7,22 @@
 artifact_dir=$(mktemp -d)
 ### TESTING
 cp imp-ci "${artifact_dir}"
+signing_target=$(ls -1 "${artifact_dir}")
 ### TESTING
 pushd "${artifact_dir}"
 
-# Retrieve the artifact to sign.
-# buildkite-agent artifact download "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}" .
-# retval=$?
-# if [[ "${retval}" -ne 0  ]]; then
-#   echo "Unable to download the specified artifact '${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}' with error code '${retval}'"
-#   exit 1
-# fi
-signing_target=$(ls -1 .)
+echo "Retrieving unsigned artifact"
+buildkite-agent artifact download "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}" .
+retval=$?
+if [[ "${retval}" -ne 0  ]]; then
+  echo "Unable to download the specified artifact '${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}' with error code '${retval}'"
+  exit 1
+fi
 
-# Unlock the keychain, since the setup set left it locked.
+# echo "Unlock the keychain"
 # security unlock-keychain -p "${KEYCHAIN_PW}" codesign.keychain
 
-# Sign it with the cert specified.
-# codesign -s "${CODESIGN_IDENTITY}" "${signing_target}"
+echo "Signing target binary"
 codesign --verify --verbose --display --deep -s "${CODESIGN_IDENTITY}" ${signing_target}
 retval=$?
 if [[ "${retval}" -ne 0  ]]; then
@@ -31,7 +30,7 @@ if [[ "${retval}" -ne 0  ]]; then
   exit 2
 fi
 
-# Validate that the target now has the expected signature.
+echo "Validating signature"
 codesign --verify --deep --strict --verbose= "${signing_target}"
 retval=$?
 if [[ "${retval}" -ne 0  ]]; then
@@ -39,10 +38,10 @@ if [[ "${retval}" -ne 0  ]]; then
   exit 3
 fi
 
-# Store the signed artifact back in the bucket.
-# buildkite-agent artifact upload "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}"
-# retval=$?
-# if [[ "${retval}" -ne 0  ]]; then
-#   echo "Unable to upload signed target '${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}' to artifact bucket with error code '${retval}'"
-#   exit 4
-# fi
+echo "Uploading signed artifact"
+buildkite-agent artifact upload "${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}" "${output_artifact}"
+retval=$?
+if [[ "${retval}" -ne 0  ]]; then
+  echo "Unable to upload signed artifact '${BUILDKITE_PLUGIN_MAC_CODESIGN_INPUT_ARTIFACT}' to artifact bucket with error code '${retval}'"
+  exit 4
+fi
